vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.opt.nu = true
vim.opt.relativenumber = true
vim.o.statuscolumn = "%s %l %r "

require("settings.helpers")
require("settings.filetype")
require("settings.rest")
require("settings.legendary")
require("settings.keybindings")
require("settings.dapui")
require("settings.dap")
require("settings.cheat")
require("settings.treesitter")
require("settings.nvim-tmux-navigation")
require("settings.aerial")
require("settings.term")
require("settings.noice")
-- require("settings.pets")
require("settings.nvim-web-devicons")
require("settings.bufferline")
require("settings.comment")
require("settings.autopairs")
require("settings.peekup")
require("settings.dbee")
require("settings.navic")
require("settings.navbuddy")
require("settings.lspconfig")
require("settings.cmp")
require("settings.nvimtree")
require("settings.snippy")
require("settings.gp")
require("settings.trouble")
require("settings.e-kaput")
require("settings.bookmarks")
require("settings.qmk")
require("settings.exrc")
require("settings.cmp-dbee")
require("settings.overseer")
require("settings.neotest")
require("settings.glow")
-- require("settings.image_preview")
require("settings.lualine")
require("settings.none-ls")
