require("settings.filetype")
require("settings.rest")
-- require("settings.noice")
require("settings.legendary")
require("settings.oterm")
require("settings.keybindings")
require("settings.dapui")
require("settings.dap")
require("settings.cheat")
require("settings.treesitter")
require("settings.harpoon")
require("settings.nvim-tmux-navigation")
require("settings.aerial")
